services:
  - type: web
    name: desk-service-piloto
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: VITE_API_BASE_URL
        value: https://SEU_BACKEND_URL
